{% set name = "groclient" %}
{% set version = "1.107.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/groclient-{{ version }}.tar.gz
  sha256: 05eb642f63cc7153bdc33cdf7f700f310bc77d82f1aaa8d542a0289a675fa1e4

build:
  number: 0
  noarch: python
  entry_points:
    - gro_client = groclient.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry-core >=1.0.0,<2.0.0
  run:
    - numpy
    - pandas
    - python >=3.6,<4.0
    - requests
    - tornado
    - unicodecsv

test:
  imports:
    - api
    - api.client
  commands:
    - pip check
    - gro_client --help
  requires:
    - pip

about:
  home: https://www.gro-intelligence.com/products/gro-api
  summary: Python client library for accessing Gro Intelligence's agricultural data platform
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jli
    - muzigao
    - nemozen
